services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'trak'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'trakuser'
    ports:
      - '5432:5432'
    restart: unless-stopped
  #    volumes:
  #      - 'trak:/var/lib/postgresql/data'
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'trak-pgadmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'



volumes:
  trak: