services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'trak'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'trakuser'
    ports:
      - '5432:5432'
    volumes:
      - 'trak:/var/lib/postgresql/data'

volumes:
  trak: